using System;
using System.Collections.Generic;
using System.Text;

namespace CosmosDemo
{
    public class Transaction
    {
        public string HeaderId { get; set; }
        public string InvestorId { get; set; }
        public string id { get; set; }
        public string Type { get; set; }
        public string Tenant { get; set; }
        public string PartitionKey { get; set; }
        public string TransactionCurrencyId { get; set; }
        public string TransactionTypeDescription { get; set; }
        public string TransactionTypeChangeType { get; set; }
        public string TransactionSecurityCode { get; set; }
        public string TransactionTypeCode { get; set; }
        public string TransactionTypeId { get; set; }
        public string PositionId { get; set; }
        public string HoldingId { get; set; }
        public string AccountId { get; set; }
        public string AskCurrencyCode { get; set; }
        public string AccountCode { get; set; }
        public string TransactionId { get; set; }
        public string TransactionCategory { get; set; }
        public string TransactionCategoryClass { get; set; }
        public string TransactionSettlementCurrencyCode { get; set; }
        public string SecurityId { get; set; }
        public string SecurityCode { get; set; }
        public string CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string SecurityTypeId { get; set; }
        public string SecurityTypeCode { get; set; }
        public string SourceId { get; set; }
        public decimal UnitBalance { get; set; }
        public decimal RemainingPrincipalBalance { get; set; }
        public decimal BookValue { get; set; }
        public decimal AskBookValue { get; set; }
        public decimal NetBookValue { get; set; }
        public decimal AskNetBookValue { get; set; }
        public decimal AdjustedBookValue { get; set; }
        public decimal AskAdjustedBookValue { get; set; }
        public decimal AccountingCost { get; set; }
        public decimal AskAccountingCost { get; set; }
        public decimal AccrualForBookValue { get; set; }
        public decimal WeightedPriceDifferenceFromPar { get; set; }
        public decimal TransactionProceeds { get; set; }
        public decimal AskTransactionSettlementAmount { get; set; }
        public decimal AskTransactionAccruedOnSettle { get; set; }
        public decimal PriceToAskingRate { get; set; }
        public decimal AskingRate { get; set; }
        public decimal SettlementToAskingRate { get; set; }
        public decimal SettlementToAskingRateOnSettle { get; set; }
        public decimal Exposure { get; set; }
        public decimal AskExposure { get; set; }
        public decimal AskTransactionPortfolioAssetFlow { get; set; }
        public decimal AskTransactionSecurityAssetFlow { get; set; }
        public decimal AskNetPortfolioAssetFlow { get; set; }
        public decimal AskNetSecurityAssetFlow { get; set; }
        public decimal AverageCost { get; set; }
        public decimal AskAverageCost { get; set; }
        public decimal InternalAskAverageCost { get; set; }
        public decimal AskTransactionPriceGainLoss { get; set; }
        public decimal AskTransactionForexGainLoss { get; set; }
        public decimal AskTransactionIncomeGainLoss { get; set; }
        public decimal AskTransactionCapitalGainLoss { get; set; }
        public decimal AskForexGainLoss { get; set; }
        public decimal AskPriceGainLoss { get; set; }
        public decimal AskIncomeGainLoss { get; set; }
        public decimal AskCapitalGainLoss { get; set; }
        public decimal AskTransactionDeemCost { get; set; }
        public decimal AskRealizedGainLoss { get; set; }
        public decimal TransactionInterestIncome { get; set; }
        public decimal AskTransactionInterestIncome { get; set; }
        public decimal AskTransactionDividendIncome { get; set; }
        public decimal AskTransactionWithHoldingTax { get; set; }
        public decimal AskUnpaidInterest { get; set; }
        public decimal InterestIncome { get; set; }
        public decimal AskDividendIncome { get; set; }
        public decimal AskWithHoldingTax { get; set; }
        public decimal AskInterestIncome { get; set; }
        public decimal YieldOnBook { get; set; }
        public decimal TransactionYieldOnBook { get; set; }
        public decimal TransactionUnits { get; set; }
        public decimal TransactionUnitsFromTransaction { get; set; }
        public decimal TransactionSettlementAmount { get; set; }
        public bool IsCash { get; set; }
        public decimal TransactionNumber { get; set; }
        public decimal TransactionSettlementRate { get; set; }
        public decimal TransactionPrice { get; set; }
        public decimal TransactionBookValue { get; set; }
        public decimal TransactionFees { get; set; }
        public decimal TransactionAccrued { get; set; }
        public decimal AskTransactionAccrued { get; set; }
        public decimal AskTransactionBookValue { get; set; }
        public decimal PreviousUnitBalance { get; set; }
        public decimal PreviousRemainingPrincipal { get; set; }
        public decimal PreviousBookValue { get; set; }
        public decimal PreviousAskBookValue { get; set; }
        public decimal PreviousAskAverageCost { get; set; }
        public decimal PreviousInternalAskAverageCost { get; set; }
        public decimal PreviousAverageCost { get; set; }
        public decimal PreviousYieldOnBook { get; set; }
        public decimal PreviousAskNetPortfolioAssetFlow { get; set; }
        public decimal PreviousAskNetSecurityAssetFlow { get; set; }
        public decimal LastBuyUnits { get; set; }
        public decimal LastSellUnits { get; set; }
        public decimal LastBuyUnitPrice { get; set; }
        public decimal LastSellUnitPrice { get; set; }
        public decimal Factor { get; set; }
        public decimal AskManagementFee { get; set; }
        public decimal AskCustfee { get; set; }
        public decimal AskCashdp { get; set; }
        public decimal AskCashwd { get; set; }
        public decimal AskCashxfrin { get; set; }
        public decimal AskCashfrout { get; set; }
        public decimal MarkToMarket { get; set; }
        public decimal AccrualForDiscountedSecurity { get; set; }
        public decimal AskAccrualForDiscountedSecurity { get; set; }
        public decimal AskSettlementAmountOnSettleDate { get; set; }
        public decimal YieldOnAdjustedBook { get; set; }
        public decimal AdjustedAverageCost { get; set; }
        public decimal AskAdjustedAverageCost { get; set; }
        public decimal AskAdjustedCapitalGainLoss { get; set; }
        public decimal AskAdjustedPriceGainLoss { get; set; }
        public decimal AskAdjustedForexGainLoss { get; set; }
        public decimal AskTransactionAdjustedDeemCost { get; set; }
        public decimal AskTransactionAdjustedCapitalGainLoss { get; set; }
        public decimal AskTransactionAdjustedPriceGainLoss { get; set; }
        public decimal AskTransactionAdjustedForexGainLoss { get; set; }
        public decimal AskCapitalGainIncome { get; set; }
        public decimal AskForeignIncome { get; set; }
        public decimal AskSecuxfrin { get; set; }
        public decimal AskSecuxfrout { get; set; }
        public decimal AskTransactionCapitalGainIncome { get; set; }
        public decimal AskTransactionForeignIncome { get; set; }
        public decimal AskSecudp { get; set; }
        public decimal AskSecuwd { get; set; }
        public decimal AskTransactionProceeds { get; set; }
        public decimal AskTransactionManagementFee { get; set; }
        public decimal AskTransactionCustfee { get; set; }
        public decimal AskMarketValueAdjustment { get; set; }
        public decimal RemainingCommitment { get; set; }
        public decimal MarketValue { get; set; }
        public decimal MarketValueBase { get; set; }
        public DateTime? FirstSettlementDate { get; set; }
        public DateTime? LastPositiveImpactDateOnAccountingCost { get; set; }
        public DateTime TradeDate { get; set; }
        public DateTime SettlementDate { get; set; }
        public DateTime EffectiveDate { get; set; }
        public DateTime LastBuyDate { get; set; }
        public DateTime LastSellDate { get; set; }
        public DateTime Born { get; set; }
    }
}
